/* eslint-disable react/no-unescaped-entities -- The hero displays literal JSON syntax. */
import Link from "next/link";
import { tools } from "@formatbase/tool-registry";

export default function Home() {
  return <main>
    <section className="hero"><div className="container hero-grid"><div>
      <div className="eyebrow"><span className="live-dot" /> BROWSER FIRST DEVELOPER TOOLS</div>
      <h1>Make sense of<br /><em>your data.</em></h1>
      <p className="hero-copy">Format, validate, and convert structured data in seconds. No upload, no account, no distractions.</p>
      <div className="hero-actions"><Link className="button primary" href="/json-formatter">Open JSON Formatter <span>↗</span></Link><a className="button secondary" href="#tools">Explore tools ↓</a></div>
      <div className="hero-proof"><span>✦ Private by design</span><span>⚡ Runs in your browser</span><span>◇ Free to use</span></div>
    </div><div className="hero-preview" aria-label="Example formatted JSON"><div className="preview-top"><span className="preview-dots"><i/><i/><i/></span><span>response.json</span><span className="preview-badge">VALID JSON</span></div><div className="preview-code"><div><b>1</b><span>{"{"}</span></div><div><b>2</b><span>  <i>"project"</i>: <strong>"formatbase"</strong>,</span></div><div><b>3</b><span>  <i>"private"</i>: <mark>true</mark>,</span></div><div><b>4</b><span>  <i>"tools"</i>: [</span></div><div><b>5</b><span>    <strong>"format"</strong>,</span></div><div><b>6</b><span>    <strong>"validate"</strong>,</span></div><div><b>7</b><span>    <strong>"minify"</strong></span></div><div><b>8</b><span>  ]</span></div><div><b>9</b><span>{"}"}</span></div></div><div className="preview-footer"><span className="green-dot" /> Processed locally in your browser <span>0.02s</span></div></div></div></section>
    <section className="tools-section container" id="tools"><div className="section-heading"><div><div className="eyebrow">THE TOOLBOX</div><h2>Everything you need.<br /><span>Nothing you don’t.</span></h2></div><p>A focused set of tools built for the work you do every day. Format JSON, SQL, YAML, and XML, or convert between structured formats, locally.</p></div><div className="tool-grid">{tools.map((tool, index) => <Link href={`/${tool.slug}`} className="tool-card" key={tool.id}><div className="card-top"><span className="card-icon">{["{ }", "✓", "≡", "↕", "⌘"][index] ?? "⌁"}</span><span className="card-arrow">↗</span></div><div className="card-eyebrow">{tool.eyebrow}</div><h3>{tool.name}</h3><p>{tool.description}</p><span className="card-link">Open tool <span>→</span></span></Link>)}</div></section>
    <section className="privacy-band"><div className="container privacy-grid"><div className="privacy-symbol">⌁</div><div><div className="eyebrow">PRIVACY IS THE DEFAULT</div><h2>Your data stays<br /><em>on your device.</em></h2><p>Everything runs in your browser. Your input is never uploaded, logged, or stored by Formatbase. Work with real data confidently.</p><Link href="/privacy">How our privacy works <span>→</span></Link></div><div className="privacy-list"><div><span>01</span><strong>Local processing</strong><p>Every operation runs in a dedicated browser worker.</p></div><div><span>02</span><strong>No account required</strong><p>Open a tool and get straight to work.</p></div><div><span>03</span><strong>Input never stored</strong><p>We do not save your pasted text or files.</p></div></div></div></section>
    <section className="bottom-cta container"><div className="eyebrow">READY WHEN YOU ARE</div><h2>Less friction.<br /><em>More flow.</em></h2><Link className="button primary" href="/json-formatter">Start formatting <span>↗</span></Link></section>
  </main>;
}
